name: Publish to PyPI

on:
  workflow_dispatch:  # This allows manual triggering
  release:
    types: [ published ]  # Optionally trigger on new releases

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        run: pip install uv

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
